apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: ericlessa/gitops-k8s-go
  newTag: 19a056863dac11201ab0432cb4e33f50389861a6
